# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_g_params <- function(GX_g, dGX_g, z_S_g, m_g, O_list, start_g, S_g, iOsigO_g, lib_mat, Y, mu_g, z, g, N) {
    .Call(`_MixPLNClust_update_g_params`, GX_g, dGX_g, z_S_g, m_g, O_list, start_g, S_g, iOsigO_g, lib_mat, Y, mu_g, z, g, N)
}

update_mu <- function(m_g, O_list, iOsigO_g, mu_g, z, d, g, N) {
    .Call(`_MixPLNClust_update_mu`, m_g, O_list, iOsigO_g, mu_g, z, d, g, N)
}

update_sig <- function(m_g, sigma_new, sigma_g, O_list, iOsigO_g, mu_g, S_g, z, d, g, N, step) {
    .Call(`_MixPLNClust_update_sig`, m_g, sigma_new, sigma_g, O_list, iOsigO_g, mu_g, S_g, z, d, g, N, step)
}

update_sig2 <- function(m_g, sigma_new, sigma_g, O_list, iOsigO_g, mu_g, S_g, z, d, g, N, step) {
    .Call(`_MixPLNClust_update_sig2`, m_g, sigma_new, sigma_g, O_list, iOsigO_g, mu_g, S_g, z, d, g, N, step)
}

PD_check <- function(sigma_new, G) {
    .Call(`_MixPLNClust_PD_check`, sigma_new, G)
}

invert_matrices <- function(sigma, i_sigma, G) {
    invisible(.Call(`_MixPLNClust_invert_matrices`, sigma, i_sigma, G))
}

compute_pi_g <- function(z, N) {
    .Call(`_MixPLNClust_compute_pi_g`, z, N)
}

create_lib_mat_full <- function(lib_mat, N) {
    .Call(`_MixPLNClust_create_lib_mat_full`, lib_mat, N)
}

compute_iOsigO <- function(O_list, sigma, iOsigO) {
    invisible(.Call(`_MixPLNClust_compute_iOsigO`, O_list, sigma, iOsigO))
}

compute_F_matrices <- function(S, m, O_list, mu, iOsigO, O_mat, Y, pi_g) {
    .Call(`_MixPLNClust_compute_F_matrices`, S, m, O_list, mu, iOsigO, O_mat, Y, pi_g)
}

aitkens_accel <- function(it, loglik, a_loglik) {
    .Call(`_MixPLNClust_aitkens_accel`, it, loglik, a_loglik)
}

